on:
  repository_dispatch

permissions:
  id-token: write
  contents: read
  attestations: write
  
jobs:
  verify_and_codesign:
    runs-on: ubuntu-latest
    env:
      S3_BUCKET: "qbt-releases/qbt-kme"
      VERSION: ${{ github.event.client_payload.version }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-1'
    steps:
        - name: Job Summary
          run: echo "Generating attestation for ${VERSION} in ${BUCKET}"
        - name: Download checksums
          run: |
            aws s3 cp s3://${S3_BUCKET}/${VERSION}/checksums.txt .
            aws s3 cp s3://${S3_BUCKET}/${VERSION}/checksums.txt.sig .
        - name: Verify checksums
          run: aws kms verify --key-id alias/github-gitlab-sigstore-bridge
               --message-type RAW
               --signing-algorithm ECDSA_SHA_512
               --message fileb://checksums.txt
               --signature fileb://checksums.txt.sig

        - name: Generate artifact attestation
          uses: actions/attest-build-provenance@v1
          with:
            subject-path: 'checksums.txt'
  

